#!/bin/bash

# Script to count SSR length using grep on an amplicons.effect file generated by rmseq
# Expected columns: mutation_id, sample, SSR_sequence (tab-delimited)
# usage rmseq_SSR_count.sh <file1> [file2 ...]

set -euo pipefail

print_sequences() {
	tail -n +2 "$1" | cut -f3
}

echo -e "sample \t 10A \t 9A \t 8A \t 7A \t 6A \t 5A \t all"

for file in "$@"; do
	if [[ ! -s "$file" ]]; then
		echo "Warning: skipping empty file $file" >&2
		continue
	fi

	sample=$(awk -F'\t' 'NR==2 {print $2; exit}' "$file")
	sample=${sample:-NA}

	ten=$(print_sequences "$file" | grep -i -c "GTGCCAAAAAAAAAATAAAG" || true)
	nine=$(print_sequences "$file" | grep -i -c "GTGCCAAAAAAAAATAAAG" || true)
	eight=$(print_sequences "$file" | grep -i -c "GTGCCAAAAAAAATAAAG" || true)
	seven=$(print_sequences "$file" | grep -i -c "GTGCCAAAAAAATAAAG" || true)
	six=$(print_sequences "$file" | grep -i -c "GTGCCAAAAAATAAAG" || true)
	five=$(print_sequences "$file" | grep -i -c "GTGCCAAAAATAAAG" || true)

	all=$(tail -n +2 "$file" | wc -l)

	echo -e "${sample} \t ${ten} \t ${nine} \t ${eight} \t ${seven} \t ${six} \t ${five} \t ${all}"
done
